config/routes.rb
Rails.application.routes.draw do

root 'pages#home'

  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get '/home', to: 'pages#home'

  # get '/recipes', to: 'recipes#index'
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes#create'
  # get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  # patch '/recipes/:id', to: 'recipes#update'
  # get 'recipes/:id', to: 'recipes#show', as: 'recipe'
  # delete '/recipes/:id', to: 'recipes#destroy'

  resources :recipes do
    member do
      post 'like'
    end
  end

  resources :chefs, except: [:new]

  get '/register', to: 'chefs#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ActiveRecord::Base
 has_many :recipes
 has_many :likes
 before_save {self.email = email.downcase}
 validates :chefname, presence: true, length: {minimum: 3, maximum: 40}
 VALID_EMAIL_REGEX = /\A[\w+\.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, presence: true, length: { maximum: 105},
                                    uniqueness: {case_sensitive: false},
                                    format: {with: VALID_EMAIL_REGEX}
# has_secure_password
end

app/models/like.rb
class Like < ActiveRecord::Base
 belongs_to :chef
 belongs_to :recipe

 validates_uniqueness_of :chef, scope: :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :chef
    has_many :likes
    validates :chef_id, presence: true
    validates :name, presence: true, length: {minimum: 5, maximum: 100}
    validates :summary, presence: true, length: {minimum: 10, maximum: 150}
    validates :description, presence: true, length: {minimum: 20, maximum: 500}
    mount_uploader :picture, PictureUploader
    validate :picture_size
    default_scope -> {order(updated_at: :desc)}

    def thumbs_up_total
        self.likes.where(like: true).size
    end

    def thumbs_down_total
        self.likes.where(like: false).size
    end

    private
        def picture_size
            if picture_size > 5.megabytes
                errors.add(:picture, "should be less than 5MB")
            end
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

    def index
        @chefs = Chef.paginate(page: params[:page], per_page: 5)
    end

    def new
        @chef = Chef.new
    end

    def create
        @chef = Chef.new(chef_params)
        if @chef.save
            flash[:success] = 'Your account has been successfully created!'
            redirect_to recipes_path
        else
            render 'new'
        end
    end

    def edit
        @chef = Chef.find(params[:id])
    end

    def update
        @chef = Chef.find(params[:id])
        if @chef.update(chef_params)
            flash[:success] = "Your profile has been updated successfully"
            redirect_to recipes_path
        else
            render 'edit'
        end
    end

    def show
        @chef = Chef.find(params[:id])
        @recipes = @chef.recipes.paginate(page: params[:page], per_page: 3)
    end


    private
    def chef_params
        params.require(:chef).permit(:chefname, :email, :password)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def index
        @recipes = Recipe.paginate(page: params[:page], per_page: 4)
    end

    def show
        @recipe = Recipe.find(params[:id])
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.chef = Chef.find(1)

        if @recipe.save
            flash[:success] = "Your recipe has been created successfully!"
            redirect_to recipes_path
        else
            render :new
        end
    end

    def edit
        @recipe = Recipe.find(params[:id])
    end

    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update(recipe_params)
            flash[:success] = "Your recipe has been updated successfully!"
            redirect_to recipes_path(@recipe)
        else
            render :edit
        end
    end

    def like
        @recipe = Recipe.find(params[:id])
        like = Like.create(like: params[:like], chef: Chef.first, recipe: @recipe)
        if like.valid?
            flash[:success] = "You like this recipe"
            redirect_to recipes_path(recipe_params)
        else
            flash[:danger] = "You already performed this action"
            redirect_to recipes_path(recipe_params)
        end
    end

    private
    def recipe_params
        params.require(:recipe).permit(:name, :summary, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(chef, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chefs/_form.html.erb
<%= form_for @chef do |f| %>
<div class='row'>
    <div class="col-lg-6">
        <div class= "form-group">
        <%= f.label :chefname, class:"form-label"%>
        <%= f.text_field :chefname, class:"form-control"%>
        </div><br>

        <div class= "form-group">
        <%= f.label :email, class:"form-label"%>
        <%= f.email_field :email, class:"form-control" %>
        </div><br>
    </div>

    <div class="col-lg-6">
        <div class= "form-group">
        <%= f.label :password, class:"form-label"%>
        <%= f.password_field :password, class:"form-control" %>
        </div><br>

        <div class= "form-group">
        <%= f.submit(@chef.new_record? ? 'Register': 'Edit profile', class: 'btn btn-success btn-block') %>  
        </div>
    </div>
</div>
<%end%>

app/views/chefs/edit.html.erb
<div class='row g-5'>
<%= render 'shared/page_title', title: "Edit your profile"%>
<%= render 'shared/error'%>
<%= render 'form', chef: @chef%>
</div>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "All Chefs"%>
<%= will_paginate %>
<% @chefs.each do |recipe| %>
<div class='row'>
    <div class='col-md-2 center'>
    <%= gravatar_for recipe.chef, size: 100 %>
    <h5> Chef name:<%= recipe.chef.chefname %></h5>
    </div>

    <div class='col-md-6 align-left'>
    <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
    <p><%= recipe.summary %></p>

    <p>
    <span class ='quiet'><small>created: <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
    <span class ='quiet'><small>updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
    </p>
    <div class="pull-right">
            <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total%>
            <% end %> &nbsp&nbsp&nbsp
            <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total%>
            <% end %>
            </div>
    </div>
    <div class="col-md-4">
    <%= image_tag(recipe.picture.url, size: "250x150", class:"gravatar") if recipe.picture? %>
    </div>
    <hr>
<%end%>
</div>
<%= will_paginate %>

app/views/chefs/new.html.erb
<div class='row g-5'>
<%= render 'shared/page_title', title: "New Recipe"%>
<%= render 'shared/error'%>
<%= render 'form', chef: @chef%>
</div>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: @chef.chefname%>
<div class='row'>
    <div class='center'>
        <%= gravatar_for @chef, size: 200 %>
    </div>
</div><hr>

<div class="row">
    <div class="center">
        <h3><em>Recipes:</em></h3>
        <%= will_paginate @recipes%>
    </div>
</div>

<% @chef.recipes.each do |recipe| %>
<div class='row'>
    <div class='center'>
    <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
    <p><%= recipe.summary %></p>

    <p>
    <span class ='quiet'><small>created: <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
    <span class ='quiet'><small>updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
    </p>
    <div class="right-align">
            <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total%>
            <% end %> &nbsp&nbsp&nbsp
            <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total%>
            <% end %>
    </div>
    </div>
 
</div>
<%end%>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-md-10">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%=message_type%>"><%=message%>
        <a class= "close" data-dismiss="alert">&#215;</a>
        </div>
    <%end%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">
  <div class="cover-container d-flex w-100 h-900 p-3 mx-auto flex-column">
    <header>
      <%= render "shared/navbar"%>
    </header>
    <main class="px-3">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </main>
    <footer class="footer mt-auto py-3 text-white">
      <%= render "shared/footer"%>
    <footer>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Find and create your recipes</h1><br>
<p class="lead">Welcome to My Recipes App. It can be for building simple and beautiful home or commercially 
                made recipes. Download, edit the recipes, and add your own photos to make it simply special.
                </p><br>
<%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success"%>
<br>

<div class="row">
    <div class="col-lg-4 left">
        <h3 class="midrow">View Recipes as Guest</h3>
        <p>Browse and view recipes as a guest and Sign Up later</p>
        <p><%= link_to "Browse Recipe Listing", recipes_path, class: "btn btn-warning btn-small"%></p>
    </div>
    <div class="col-lg-4 left">
        <h3 class="midrow">Create Recipes as Guest</h3>
        <p>Browse and view recipes as a guest and Sign Up later</p>
        <p><%= link_to "Create a new Recipe", new_recipe_path, class: "btn btn-warning btn-small"%></p>
    </div>
    <div class="col-lg-4 left">
        <h3 class="midrow">View Recipes as Guest</h3>
        <p>Browse and view recipes as a guest and Sign Up later</p>
        <p><%= link_to "Login to your account", "", class: "btn btn-warning btn-small"%></p>
    </div>
</div>

app/views/recipes/_form.html.erb
<%= form_for(@recipe, html: { multipart:true}) do |f| %>
<div class='row'>
    <div class="col-lg-6">
        <div class= "form-group">
        <%= f.label :name, class:"form-label"%>
        <%= f.text_field :name, class:"form-control"%>
        </div><br>

        <div class= "form-group">
        <%= f.label :summary, class:"form-label"%>
        <%= f.text_area :summary, class:"form-control",rows:6%>
        </div><br>

        <span class="picture">
        <%=f.file_field :picture, accept: "image/jpeg,image/gif,/image/png"%>
        </span>

    </div>
    <div class="col-lg-6">
        <div class= "form-group">
        <%= f.label :description, class:"form-label"%>
        <%= f.text_area :description, class:"form-control",rows: 12%>
        </div><br>

        <div class= "form-group">
        <%= f.submit(@recipe.new_record? ? 'Create Recipe': 'Update Recipe', class: 'btn btn-success btn-block') %>  
        </div>
    </div>
</div>
<%end%>

<script type="text/javascript">
$ (document).ready(function () {
    $('#recipe_picture').bind('change', function() {
        console.log('Go fuck your self');
        size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5){
        alert('Maximum file size is 5MB. Please choose a smaller file');
    }
    });
});
</script>

app/views/recipes/edit.html.erb
<div class='row g-5'>
<%= render 'shared/page_title', title: "Edit Recipe"%>
<%= render 'shared/error'%>
<%= render 'form', recipe: @recipe%>
</div>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes"%>
<% @recipes.each do |recipe| %>
    <div class="col-md-2">
        <section class="chef_info center">
            <%= gravatar_for recipe.chef, size: 100 %>
            <h5> Chef name:<%= recipe.chef.chefname %></h5>
        </section>
    </div>
    <div class= "col-md-8 well">
    <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
    <p><%= recipe.summary %></p>

    <p>
    <span class ='quiet'><small><%= time_ago_in_words(recipe.created_at)%>ago</small></span>
    </p>
    </div>
    <hr>
</div>
<%end%>

app/views/recipes/new.html.erb
<div class='row g-5'>
<%= render 'shared/page_title', title: "Register your account"%>
<%= render 'shared/error'%>
<%= render 'form', recipe: @recipe%>
</div>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name%>

<div class='row'>
    <div class='col-md-4 pull-right center'>
        <%= link_to gravatar_for(@recipe.chef, size: 200), chef_path(@recipe.chef) %>
        <p>
        <h5>Created by: <%=@recipe.chef.chefname%></h5>
        </p>
    </div>
    <div class='col-md-8 align-left'>
    
        <h3><%= @recipe.summary%></h3>
        <div class="show_recipe">
        <%= image_tag(@recipe.picture.url, class:"gravatar") if @recipe.picture? %>
        </div>
        <div class='well'>
            <p>
            <strong>Steps:</strong>
            </p>
            <%= simple_format(@recipe.description) %>
            <div class="pull-right">
            <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @recipe.thumbs_up_total%>
            <% end %> &nbsp&nbsp&nbsp
            <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @recipe.thumbs_down_total%>
            <% end %>
            </div>
        </div>
    </div>
</div>

<%= link_to 'Edit this recipe', edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
<%= link_to "Back to Recipes List", recipes_path, class: "btn btn-warning btn-small" %>

app/views/shared/_error.html.erb
<% if @chef.errors.any? %>
<div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
        <h5>Please correct the following errors:</h5>
        <ul>
        <% @chef.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <%end%>
        </ul>
    </div>
</div>
<%end%>

app/views/shared/_footer.html.erb
<div class="container">
    <span class="text-muted">@copyright</span>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark" aria-label="Fourth navbar example">
    <div class="container-fluid">
      <%= link_to "My Recipes", root_path, class: "btn btn-lg btn-success "%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample04">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown04">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <form>
          <input class="form-control" type="text" placeholder="Find my recipe" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>

app/views/shared/_page_title.html.erb
<h1><%=title%></h1>
<hr/>

app/views/shared/_slider.html.erb
    <h1>Cover your page.</h1>
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
    </p>